title: GT Big Data Wiki
description: GT Big Data Club's trove of knowledge
show_github: false
comments: false
logo_url: https://avatars3.githubusercontent.com/u/6249784?s=200&v=4
git_branch: gh-pages
theme:
use_github_wiki: false
use_prose_io: true
custom_sidebar: true
plugins:
  - jekyll-sitemap
  - jekyll-titles-from-headings
pages: ./wiki
